version: '2'

services:
  nginx:
    image: nginx:latest
  warp:
    image: taichunmin/cloudflare-warp:latest
    volumes:
      - ./cloudflare-warp:/root/.cloudflare-warp
    environment:
      - WRAP_HOSTNAME=${WRAP_HOSTNAME}
      - WRAP_URL=http://nginx